export const VISA_CONFIG = {
  USA: {
    name: "United States",
    visas: {
      "B1/B2 Tourism": {
        displayName: "B1/B2 Tourism",
        requiredDocuments: ["Passport", "Bank Statement", "Travel Itinerary"],
        optionalDocuments: ["Employment Letter", "Property Deed", "Travel History"],
        processingTime: "3-6 months",
        successRate: 72,
      },
      "H1B Work": {
        displayName: "H1B Work Visa",
        requiredDocuments: ["Passport", "Bank Statement", "Employment Letter", "Degree Certificate"],
        optionalDocuments: ["Project Portfolio", "Publications", "Professional Certifications"],
        processingTime: "2-3 months",
        successRate: 68,
      },
      "O-1A": {
        displayName: "O-1A Extraordinary Ability (Individuals)",
        requiredDocuments: ["Passport", "Evidence of Extraordinary Ability (awards/publications)", "Recommendation Letters", "Employment Offer/Contract"],
        optionalDocuments: ["Press Clippings", "Professional Memberships", "Portfolio"],
        processingTime: "2-4 months",
        successRate: 60,
      },
      "O-1B": {
        displayName: "O-1B Extraordinary Ability (Arts/Entertainment)",
        requiredDocuments: ["Passport", "Evidence of Extraordinary Ability in Arts", "Recommendation Letters", "Employment Offer/Contract"],
        optionalDocuments: ["Press Reviews", "Portfolio", "Awards"],
        processingTime: "2-4 months",
        successRate: 58,
      },
      "F1 Student": {
        displayName: "F1 Student Visa",
        requiredDocuments: ["Passport", "I-20 Form", "Bank Statement", "Degree Certificate"],
        optionalDocuments: ["Test Scores", "Transcripts", "Research Papers"],
        processingTime: "2-4 weeks",
        successRate: 85,
      },
      "EB Green Card": {
        displayName: "EB Green Card",
        requiredDocuments: [
          "Passport",
          "Bank Statements (2 years)",
          "Employment Records",
          "Degree Certificate",
          "Police Clearance",
        ],
        optionalDocuments: ["Tax Returns", "Property Documents", "Publications"],
        processingTime: "6-12 months",
        successRate: 55,
      },
    },
  },
  Canada: {
    name: "Canada",
    visas: {
      "Visitor Visa": {
        displayName: "Visitor Visa",
        requiredDocuments: ["Passport", "Financial Proof", "Travel Plan"],
        optionalDocuments: ["Employment Letter", "Property Deed", "Invitation Letter"],
        processingTime: "2-4 months",
        successRate: 70,
      },
      "Work Permit": {
        displayName: "Work Permit",
        requiredDocuments: ["Passport", "Job Offer", "Educational Credential", "Medical Exam"],
        optionalDocuments: ["Employment Experience Letter", "Language Test Results", "References"],
        processingTime: "2-3 months",
        successRate: 72,
      },
      "Study Permit": {
        displayName: "Study Permit",
        requiredDocuments: ["Passport", "Acceptance Letter", "Bank Statement", "Degree Certificate"],
        optionalDocuments: ["Language Test Results", "Transcripts", "Essay"],
        processingTime: "4-8 weeks",
        successRate: 80,
      },
      "Express Entry": {
        displayName: "Express Entry",
        requiredDocuments: ["Passport", "Language Test Results", "Educational Credentials", "Work Experience Records"],
        optionalDocuments: ["Provincial Nomination", "Job Offer", "Provincial Language Test"],
        processingTime: "6 months",
        successRate: 65,
      },
    },
  },
  UK: {
    name: "United Kingdom",
    visas: {
      "Standard Visitor": {
        displayName: "Standard Visitor Visa",
        requiredDocuments: ["Passport", "Bank Statements (6 months)", "Travel Itinerary"],
        optionalDocuments: ["Employment Letter", "Property Deed", "Sponsor Letter"],
        processingTime: "3-8 weeks",
        successRate: 75,
      },
      "Work Visa": {
        displayName: "Skilled Worker Visa",
        requiredDocuments: ["Passport", "Job Offer", "Sponsorship Certificate", "Degree Certificate", "Bank Statement"],
        optionalDocuments: ["Project Portfolio", "References", "Language Certificate"],
        processingTime: "8-12 weeks",
        successRate: 70,
      },
      "Student Visa": {
        displayName: "Student Visa",
        requiredDocuments: ["Passport", "Acceptance Letter", "Bank Statement", "Degree Certificate"],
        optionalDocuments: ["Language Test Results", "Previous Institution Records", "Financial Support Letter"],
        processingTime: "4-6 weeks",
        successRate: 82,
      },
      Settlement: {
        displayName: "Indefinite Leave to Remain",
        requiredDocuments: [
          "Passport",
          "Police Clearance",
          "Bank Statements (2 years)",
          "Medical Exam",
          "Employment Records",
        ],
        optionalDocuments: ["Tax Returns", "Property Documents", "Community Service Records"],
        processingTime: "12+ months",
        successRate: 60,
      },
    },
  },
  Germany: {
    name: "Germany",
    visas: {
      "Tourist Visa": {
        displayName: "Schengen Tourist Visa",
        requiredDocuments: ["Passport", "Proof of Funds", "Travel Itinerary", "Accommodation Booking"],
        optionalDocuments: ["Employment Letter", "Previous Visa Stamps", "Return Flight Booking"],
        processingTime: "2-3 weeks",
        successRate: 78,
      },
      "EU Blue Card": {
        displayName: "EU Blue Card",
        requiredDocuments: ["Passport", "Job Offer", "Degree Certificate", "Bank Statement"],
        optionalDocuments: ["Professional Certifications", "Publications", "Experience Letters"],
        processingTime: "4-8 weeks",
        successRate: 72,
      },
      "ICT Permit": {
        displayName: "ICT Permit (Intra-Corporate Transfer)",
        requiredDocuments: [
          "Passport",
          "Job Offer from Multinational Company",
          "Degree Certificate",
          "Work Experience (3+ years)",
        ],
        optionalDocuments: ["Project Portfolio", "Language Certificate", "Recommendations"],
        processingTime: "4-6 weeks",
        successRate: 75,
      },
      "Student Visa": {
        displayName: "Student Visa",
        requiredDocuments: ["Passport", "University Admission Letter", "Bank Statement", "German Language Proof"],
        optionalDocuments: ["Previous Academic Records", "Health Insurance Confirmation", "Motivation Letter"],
        processingTime: "2-4 weeks",
        successRate: 85,
      },
    },
  },
  Ireland: {
    name: "Ireland",
    visas: {
      "Critical Skills Employment Permit": {
        displayName: "Critical Skills Employment Permit",
        requiredDocuments: ["Passport", "Job Offer", "Degree Certificate", "Bank Statement", "Employment Contract"],
        optionalDocuments: ["Professional Certifications", "Work Experience Letters", "Project Portfolio"],
        processingTime: "4-6 weeks",
        successRate: 74,
      },
      "General Employment Permit": {
        displayName: "General Employment Permit",
        requiredDocuments: ["Passport", "Job Offer", "Bank Statement", "Employment Contract"],
        optionalDocuments: ["Degree Certificate", "Work Experience Letters", "Professional References"],
        processingTime: "4-8 weeks",
        successRate: 70,
      },
      "Student Visa": {
        displayName: "Student Visa",
        requiredDocuments: [
          "Passport",
          "University Admission Letter",
          "Bank Statement (€7,000 minimum)",
          "Degree Certificate",
        ],
        optionalDocuments: ["Language Test Results", "Health Insurance", "Accommodation Proof"],
        processingTime: "2-4 weeks",
        successRate: 83,
      },
      "Visitor Visa": {
        displayName: "Visitor Visa",
        requiredDocuments: ["Passport", "Bank Statement", "Return Flight Booking", "Travel Itinerary"],
        optionalDocuments: ["Employment Letter", "Accommodation Proof", "Sponsorship Letter"],
        processingTime: "2-3 weeks",
        successRate: 76,
      },
    },
  },
  Poland: {
    name: "Poland",
    visas: {
      "Work Permit Type C": {
        displayName: "Work Permit Type C",
        requiredDocuments: ["Passport", "Job Offer", "Employment Contract", "Degree Certificate", "Bank Statement"],
        optionalDocuments: ["Professional Certifications", "Work Experience Letters", "Medical Exam"],
        processingTime: "3-4 weeks",
        successRate: 71,
      },
      "Digital Nomad Visa": {
        displayName: "Digital Nomad Visa",
        requiredDocuments: ["Passport", "Bank Statement (€2,000/month)", "Remote Work Proof", "Health Insurance"],
        optionalDocuments: ["Tax Returns", "Client Contracts", "Portfolio"],
        processingTime: "2-3 weeks",
        successRate: 79,
      },
      "Student Visa": {
        displayName: "Student Visa",
        requiredDocuments: ["Passport", "University Admission Letter", "Bank Statement", "Degree Certificate"],
        optionalDocuments: ["Language Test", "Health Insurance", "Accommodation Booking"],
        processingTime: "2-3 weeks",
        successRate: 84,
      },
      "Tourist Visa": {
        displayName: "Schengen Tourist Visa",
        requiredDocuments: ["Passport", "Bank Statement", "Travel Itinerary", "Accommodation Booking"],
        optionalDocuments: ["Employment Letter", "Invitation Letter", "Return Flight"],
        processingTime: "2-3 weeks",
        successRate: 80,
      },
    },
  },
  France: {
    name: "France",
    visas: {
      "Talent Passport": {
        displayName: "Talent Passport",
        requiredDocuments: ["Passport", "Degree Certificate", "Bank Statement", "Professional Achievement Evidence"],
        optionalDocuments: ["Publications", "Awards", "Project Portfolio", "Professional References"],
        processingTime: "6-8 weeks",
        successRate: 68,
      },
      "Salarié en Mission": {
        displayName: "Salarié en Mission (Employee on Assignment)",
        requiredDocuments: ["Passport", "Job Offer", "Employment Contract", "Degree Certificate", "Bank Statement"],
        optionalDocuments: ["Company Documents", "Project Details", "Work Experience Letters"],
        processingTime: "4-6 weeks",
        successRate: 72,
      },
      "Student Visa": {
        displayName: "Student Visa",
        requiredDocuments: ["Passport", "University Admission Letter", "Bank Statement", "Degree Certificate"],
        optionalDocuments: ["French Language Proof", "Health Insurance", "Campus France Approval"],
        processingTime: "3-4 weeks",
        successRate: 81,
      },
      "Visitor Visa": {
        displayName: "Schengen Visitor Visa",
        requiredDocuments: ["Passport", "Bank Statement", "Travel Itinerary", "Accommodation Proof"],
        optionalDocuments: ["Employment Letter", "Return Flight", "Sponsorship Letter"],
        processingTime: "2-3 weeks",
        successRate: 77,
      },
    },
  },
  Netherlands: {
    name: "Netherlands",
    visas: {
      "Knowledge Migrant Permit": {
        displayName: "Knowledge Migrant Permit",
        requiredDocuments: ["Passport", "Job Offer", "Degree Certificate", "Bank Statement", "Employment Contract"],
        optionalDocuments: ["Professional Certifications", "Work Experience Letters", "Project Portfolio"],
        processingTime: "2-4 weeks",
        successRate: 76,
      },
      "Highly Skilled Migrant": {
        displayName: "Highly Skilled Migrant Visa",
        requiredDocuments: ["Passport", "Job Offer", "Degree Certificate", "Bank Statement", "Medical Exam"],
        optionalDocuments: ["Professional References", "Publications", "Language Certificate"],
        processingTime: "2-3 weeks",
        successRate: 78,
      },
      "Student Visa": {
        displayName: "Student Visa",
        requiredDocuments: [
          "Passport",
          "University Admission Letter",
          "Bank Statement (€15,000 annually)",
          "Degree Certificate",
        ],
        optionalDocuments: ["Health Insurance", "Language Test", "Financial Support Letter"],
        processingTime: "2-3 weeks",
        successRate: 86,
      },
      "Visitor Visa": {
        displayName: "Schengen Visitor Visa",
        requiredDocuments: ["Passport", "Bank Statement", "Travel Itinerary", "Accommodation Booking"],
        optionalDocuments: ["Employment Letter", "Return Flight", "Invitation Letter"],
        processingTime: "2 weeks",
        successRate: 82,
      },
    },
  },
  Australia: {
    name: "Australia",
    visas: {
      "Visitor Visa": {
        displayName: "Visitor Visa",
        requiredDocuments: ["Passport", "Financial Declaration", "Travel Itinerary"],
        optionalDocuments: ["Employment Letter", "Property Deed", "Previous Visa Stamps"],
        processingTime: "2-8 weeks",
        successRate: 70,
      },
      "Work Visa": {
        displayName: "Skilled Migration Visa",
        requiredDocuments: [
          "Passport",
          "Employment History",
          "Qualification Certificate",
          "Bank Statement",
          "Police Clearance",
        ],
        optionalDocuments: ["Language Test", "Skills Assessment", "Employer Sponsorship Letter"],
        processingTime: "8-16 weeks",
        successRate: 62,
      },
      "Student Visa": {
        displayName: "Student Visa",
        requiredDocuments: ["Passport", "Acceptance Letter", "Bank Statement (AUD 20,000+)", "Degree Certificate"],
        optionalDocuments: ["Language Test", "Health Insurance", "Financial Support Document"],
        processingTime: "4-12 weeks",
        successRate: 75,
      },
      Migration: {
        displayName: "Permanent Migration",
        requiredDocuments: [
          "Passport",
          "Qualification Certificate",
          "Employment Records (10+ years)",
          "Bank Statements (2 years)",
          "Police Clearance",
        ],
        optionalDocuments: ["IELTS Results", "Skill Assessment Report", "Nomination Letter"],
        processingTime: "12-24 months",
        successRate: 48,
      },
    },
  },
  UAE: {
    name: "United Arab Emirates",
    visas: {
      "Golden Visa (3 years)": {
        displayName: "Golden Visa (3 years)",
        requiredDocuments: ["Passport", "Bank Statement", "Employment Contract", "Degree Certificate"],
        optionalDocuments: ["Property Ownership Documents", "Investment Proof", "Professional License"],
        processingTime: "2-4 weeks",
        successRate: 89,
      },
      "Employment Visa": {
        displayName: "Employment Visa",
        requiredDocuments: ["Passport", "Job Offer", "Bank Statement", "Medical Exam", "Educational Qualification"],
        optionalDocuments: ["Work Experience Certificate", "Professional References", "Police Clearance"],
        processingTime: "1-2 weeks",
        successRate: 92,
      },
      "Tourist Visa": {
        displayName: "Tourist Visa",
        requiredDocuments: ["Passport", "Bank Statement", "Return Flight Booking", "Accommodation Proof"],
        optionalDocuments: ["Employment Letter", "Hotel Reservation", "Travel History"],
        processingTime: "1-2 days",
        successRate: 95,
      },
      "Investor Visa": {
        displayName: "Investor Visa",
        requiredDocuments: [
          "Passport",
          "Investment Proof (AED 500,000+)",
          "Bank Statements",
          "Business Plan",
          "Educational Background",
        ],
        optionalDocuments: ["Company Registration", "Tax Returns", "Professional References"],
        processingTime: "4-6 weeks",
        successRate: 76,
      },
    },
  },
  Qatar: {
    name: "Qatar",
    visas: {
      "Employment Visa": {
        displayName: "Employment Visa",
        requiredDocuments: ["Passport", "Job Offer", "Bank Statement", "Medical Exam", "Educational Certificate"],
        optionalDocuments: ["Employer Sponsorship Letter", "Work Experience Certificate", "Professional References"],
        processingTime: "2-3 weeks",
        successRate: 88,
      },
      "Investor Visa": {
        displayName: "Investor Visa",
        requiredDocuments: [
          "Passport",
          "Investment Proof (QAR 1,000,000+)",
          "Business Plan",
          "Bank Statements",
          "Educational Background",
        ],
        optionalDocuments: ["Company Documents", "Market Analysis", "Professional References"],
        processingTime: "4-8 weeks",
        successRate: 70,
      },
      "Tourist Visa": {
        displayName: "Tourist Visa",
        requiredDocuments: ["Passport", "Bank Statement", "Return Flight Booking", "Accommodation Proof"],
        optionalDocuments: ["Employment Letter", "Travel History", "Invitation Letter"],
        processingTime: "1-2 days",
        successRate: 93,
      },
      "Family Visa": {
        displayName: "Family/Dependent Visa",
        requiredDocuments: [
          "Passport",
          "Sponsorship Letter",
          "Bank Statement",
          "Marriage/Birth Certificate",
          "Medical Exam",
        ],
        optionalDocuments: ["Accommodation Proof", "Employment Letter", "Police Clearance"],
        processingTime: "2-4 weeks",
        successRate: 85,
      },
    },
  },
  Test: {
    name: "Test Country",
    visas: {
      "Resume-Only": {
        displayName: "Resume Only (Test)",
        requiredDocuments: ["Resume"],
        optionalDocuments: [],
        processingTime: "Instant",
        successRate: 100,
      },
    },
  },
}

export const EVALUATION_CONFIG = {
  MAX_SCORE_CAP: 85,
  MIN_SCORE: 0,
  SCORING_WEIGHTS: {
    requiredDocuments: 0.5,
    optionalDocuments: 0.2,
    visaTypeMatch: 0.2,
    profileScore: 0.1,
  },
}

export const PARTNER_CONFIG = {
  ALLOW_API_ACCESS: true,
  RATE_LIMIT_REQUESTS_PER_HOUR: 1000,
}
