"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

const translations = {
    en: {
        home: {
            badge: "AI-Powered Visa Assessment",
            title: "Your Visa Journey Starts Here",
            subtitle:
                "Get an instant evaluation of your visa eligibility with our advanced assessment tool. Know your chances before you apply.",
            cta: "Get Started",
            stat1: { value: "100%", label: "Secure & Private" },
            stat2: { value: "94%", label: "Success Rate" },
            stat3: { value: "50K+", label: "Evaluations" },
            stat4: { value: "25+", label: "Countries" },
            form: {
                title: "Start Your Evaluation",
                subtitle: "Fill in your details to receive an instant visa eligibility assessment",
            },
        },
        results: {
            title: "Visa Evaluation Report",
            downloadPdf: "Download PDF",
            downloading: "Downloading...",
            copyIframe: "Copy Iframe",
            copied: "Copied!",
            apiKey: "API Key",
            newEvaluation: "New Evaluation",
            score: "Evaluation Score",
            summary: "Summary",
            strengths: "Strengths",
            improvements: "Areas for Improvement",
            recommendation: "Recommendation",
            nextSteps: "Next Steps",
            timeline: "Timeline",
            additionalNotes: "Additional Notes",
            downloadFailed: "Failed to download report",
            another: "Start Another Evaluation",
        },
        form: {
            name: "Name",
            email: "Email",
            country: "Country",
            visaType: "Visa Type",
            selectCountry: "Select country",
            selectVisaType: "Select visa type",
            uploadDocuments: "Upload Documents",
            dragDrop: "Drag and drop files here or click to browse",
            required: "Required",
            optional: "Optional",
            submitEvaluation: "Submit for Evaluation",
            submitting: "Submitting...",
            nameRequired: "Name is required",
            emailRequired: "Email is required",
            emailInvalid: "Invalid email format",
            countryRequired: "Country is required",
            visaTypeRequired: "Visa type is required",
            documentsRequired: "Upload at least one required document",
            remove: "Remove",
        },
        evaluation: {
            invalidLink: "Invalid link",
            notFound: "We couldn't find an evaluation for the provided link.",
            ensureValid: "Ensure you are using a valid report URL.",
            loadingResults: "Loading your results...",
            pleasewait: "Please wait while we fetch your evaluation.",
            progressTitle: "Evaluation Progress",
            failedTitle: "Evaluation could not be completed",
            failedMsg: "One or more documents were found to be invalid or unreadable. Please re-upload the required documents.",
            backHome: "Back to Home",
            returnHome: "Return Home",
        },
    },
    es: {
        home: {
            badge: "Evaluación de Visa Impulsada por IA",
            title: "Tu Viaje de Visa Comienza Aquí",
            subtitle:
                "Obtén una evaluación instantánea de tu elegibilidad de visa con nuestra herramienta de evaluación avanzada. Conoce tus posibilidades antes de solicitar.",
            cta: "Comenzar",
            stat1: { value: "100%", label: "Seguro y Privado" },
            stat2: { value: "94%", label: "Tasa de Éxito" },
            stat3: { value: "50K+", label: "Evaluaciones" },
            stat4: { value: "25+", label: "Países" },
            form: {
                title: "Comienza Tu Evaluación",
                subtitle: "Completa tus detalles para recibir una evaluación de elegibilidad de visa instantánea",
            },
        },
        results: {
            title: "Informe de Evaluación de Visa",
            downloadPdf: "Descargar PDF",
            downloading: "Descargando...",
            copyIframe: "Copiar Iframe",
            copied: "¡Copiado!",
            apiKey: "Clave API",
            newEvaluation: "Nueva Evaluación",
            score: "Puntuación de Evaluación",
            summary: "Resumen",
            strengths: "Fortalezas",
            improvements: "Áreas de Mejora",
            recommendation: "Recomendación",
            nextSteps: "Próximos Pasos",
            timeline: "Cronología",
            additionalNotes: "Notas Adicionales",
            downloadFailed: "Error al descargar el informe",
            another: "Comenzar Otra Evaluación",
        },
        form: {
            name: "Nombre",
            email: "Correo Electrónico",
            country: "País",
            visaType: "Tipo de Visa",
            selectCountry: "Seleccionar país",
            selectVisaType: "Seleccionar tipo de visa",
            uploadDocuments: "Subir Documentos",
            dragDrop: "Arrastra y suelta archivos aquí o haz clic para buscar",
            required: "Requerido",
            optional: "Opcional",
            submitEvaluation: "Enviar para Evaluación",
            submitting: "Enviando...",
            nameRequired: "El nombre es obligatorio",
            emailRequired: "El correo electrónico es obligatorio",
            emailInvalid: "Formato de correo electrónico no válido",
            countryRequired: "El país es obligatorio",
            visaTypeRequired: "El tipo de visa es obligatorio",
            documentsRequired: "Sube al menos un documento requerido",
            remove: "Eliminar",
        },
        evaluation: {
            invalidLink: "Enlace no válido",
            notFound: "No pudimos encontrar una evaluación para el enlace proporcionado.",
            ensureValid: "Asegúrese de estar usando una URL de informe válida.",
            loadingResults: "Cargando tus resultados...",
            pleasewait: "Por favor espera mientras obtenemos tu evaluación.",
        },
    },
    fr: {
        home: {
            badge: "Évaluation de Visa Alimentée par l'IA",
            title: "Votre Parcours Visa Commence Ici",
            subtitle:
                "Obtenez une évaluation instantanée de votre admissibilité aux visas avec notre outil d'évaluation avancé. Connaissez vos chances avant de postuler.",
            cta: "Commencer",
            stat1: { value: "100%", label: "Sécurisé et Privé" },
            stat2: { value: "94%", label: "Taux de Réussite" },
            stat3: { value: "50K+", label: "Évaluations" },
            stat4: { value: "25+", label: "Pays" },
            form: {
                title: "Commencez Votre Évaluation",
                subtitle: "Remplissez vos coordonnées pour recevoir une évaluation instantanée de l'admissibilité aux visas",
            },
        },
        results: {
            title: "Rapport d'Évaluation de Visa",
            downloadPdf: "Télécharger PDF",
            downloading: "Téléchargement...",
            copyIframe: "Copier Iframe",
            copied: "Copié!",
            apiKey: "Clé API",
            newEvaluation: "Nouvelle Évaluation",
            score: "Score d'Évaluation",
            summary: "Résumé",
            strengths: "Forces",
            improvements: "Axes d'Amélioration",
            recommendation: "Recommandation",
            nextSteps: "Prochaines Étapes",
            timeline: "Chronologie",
            additionalNotes: "Notes Supplémentaires",
            downloadFailed: "Échec du téléchargement du rapport",
            another: "Commencer une Autre Évaluation",
        },
        form: {
            name: "Nom",
            email: "Email",
            country: "Pays",
            visaType: "Type de Visa",
            selectCountry: "Sélectionner un pays",
            selectVisaType: "Sélectionner le type de visa",
            uploadDocuments: "Télécharger des Documents",
            dragDrop: "Glissez-déposez les fichiers ici ou cliquez pour parcourir",
            required: "Requis",
            optional: "Optionnel",
            submitEvaluation: "Soumettre pour Évaluation",
            submitting: "Envoi en cours...",
            nameRequired: "Le nom est requis",
            emailRequired: "L'email est requis",
            emailInvalid: "Format d'email invalide",
            countryRequired: "Le pays est requis",
            visaTypeRequired: "Le type de visa est requis",
            documentsRequired: "Téléchargez au moins un document requis",
            remove: "Supprimer",
        },
        evaluation: {
            invalidLink: "Lien invalide",
            notFound: "Nous n'avons pas pu trouver d'évaluation pour le lien fourni.",
            ensureValid: "Assurez-vous d'utiliser une URL de rapport valide.",
            loadingResults: "Chargement de vos résultats...",
            pleasewait: "Veuillez patienter pendant que nous récupérons votre évaluation.",
        },
    },
    de: {
        home: {
            badge: "KI-gestützte Visabewertung",
            title: "Ihre Visareise Beginnt Hier",
            subtitle:
                "Erhalten Sie eine sofortige Bewertung Ihrer Visa-Berechtigung mit unserem fortschrittlichen Bewertungstool. Kennen Sie Ihre Chancen, bevor Sie sich bewerben.",
            cta: "Beginnen",
            stat1: { value: "100%", label: "Sicher & Privat" },
            stat2: { value: "94%", label: "Erfolgsrate" },
            stat3: { value: "50K+", label: "Bewertungen" },
            stat4: { value: "25+", label: "Länder" },
            form: {
                title: "Starten Sie Ihre Bewertung",
                subtitle: "Füllen Sie Ihre Daten aus, um eine sofortige Visaberechtigung-Bewertung zu erhalten",
            },
        },
        results: {
            title: "Visabewertungsbericht",
            downloadPdf: "PDF herunterladen",
            downloading: "Herunterladen...",
            copyIframe: "Iframe kopieren",
            copied: "Kopiert!",
            apiKey: "API-Schlüssel",
            newEvaluation: "Neue Bewertung",
            score: "Bewertungspunktzahl",
            summary: "Zusammenfassung",
            strengths: "Stärken",
            improvements: "Verbesserungsbereiche",
            recommendation: "Empfehlung",
            nextSteps: "Nächste Schritte",
            timeline: "Zeitplan",
            additionalNotes: "Zusätzliche Hinweise",
            downloadFailed: "Fehler beim Herunterladen des Berichts",
            another: "Eine Weitere Bewertung Starten",
        },
        form: {
            name: "Name",
            email: "E-Mail",
            country: "Land",
            visaType: "Visumart",
            selectCountry: "Land auswählen",
            selectVisaType: "Visumart auswählen",
            uploadDocuments: "Dokumente hochladen",
            dragDrop: "Dateien hier ablegen oder klicken zum Durchsuchen",
            required: "Erforderlich",
            optional: "Optional",
            submitEvaluation: "Zur Bewertung einreichen",
            submitting: "Wird eingereicht...",
            nameRequired: "Name ist erforderlich",
            emailRequired: "E-Mail ist erforderlich",
            emailInvalid: "Ungültiges E-Mail-Format",
            countryRequired: "Land ist erforderlich",
            visaTypeRequired: "Visumart ist erforderlich",
            documentsRequired: "Laden Sie mindestens ein erforderliches Dokument hoch",
            remove: "Entfernen",
        },
        evaluation: {
            invalidLink: "Ungültiger Link",
            notFound: "Wir konnten keine Bewertung für den angegebenen Link finden.",
            ensureValid: "Stellen Sie sicher, dass Sie eine gültige Berichts-URL verwenden.",
            loadingResults: "Ihre Ergebnisse werden geladen...",
            pleasewait: "Bitte warten Sie, während wir Ihre Bewertung abrufen.",
        },
    },
    pt: {
        home: {
            badge: "Avaliação de Visto Alimentada por IA",
            title: "Sua Jornada de Visto Começa Aqui",
            subtitle:
                "Obtenha uma avaliação instantânea de sua elegibilidade de visto com nossa ferramenta de avaliação avançada. Conhece suas chances antes de se candidatar.",
            cta: "Começar",
            stat1: { value: "100%", label: "Seguro e Privado" },
            stat2: { value: "94%", label: "Taxa de Sucesso" },
            stat3: { value: "50K+", label: "Avaliações" },
            stat4: { value: "25+", label: "Países" },
            form: {
                title: "Comece Sua Avaliação",
                subtitle: "Preencha seus detalhes para receber uma avaliação instantânea de elegibilidade de visto",
            },
        },
        results: {
            title: "Relatório de Avaliação de Visto",
            downloadPdf: "Baixar PDF",
            downloading: "Baixando...",
            copyIframe: "Copiar Iframe",
            copied: "Copiado!",
            apiKey: "Chave API",
            newEvaluation: "Nova Avaliação",
            score: "Pontuação de Avaliação",
            summary: "Resumo",
            strengths: "Pontos Fortes",
            improvements: "Áreas de Melhoria",
            recommendation: "Recomendação",
            nextSteps: "Próximos Passos",
            timeline: "Cronograma",
            additionalNotes: "Notas Adicionais",
            downloadFailed: "Falha ao baixar o relatório",
            another: "Iniciar Outra Avaliação",
        },
        form: {
            name: "Nome",
            email: "Email",
            country: "País",
            visaType: "Tipo de Visto",
            selectCountry: "Selecionar país",
            selectVisaType: "Selecionar tipo de visto",
            uploadDocuments: "Enviar Documentos",
            dragDrop: "Arraste e solte arquivos aqui ou clique para navegar",
            required: "Obrigatório",
            optional: "Opcional",
            submitEvaluation: "Enviar para Avaliação",
            submitting: "Enviando...",
            nameRequired: "Nome é obrigatório",
            emailRequired: "Email é obrigatório",
            emailInvalid: "Formato de email inválido",
            countryRequired: "País é obrigatório",
            visaTypeRequired: "Tipo de visto é obrigatório",
            documentsRequired: "Envie pelo menos um documento obrigatório",
            remove: "Remover",
        },
        evaluation: {
            invalidLink: "Link inválido",
            notFound: "Não conseguimos encontrar uma avaliação para o link fornecido.",
            ensureValid: "Certifique-se de estar usando uma URL de relatório válida.",
            loadingResults: "Carregando seus resultados...",
            pleasewait: "Aguarde enquanto buscamos sua avaliação.",
        },
    },
    ar: {
        home: {
            badge: "تقييم التأشيرة بقوة الذكاء الاصطناعي",
            title: "تبدأ رحلة التأشيرة الخاصة بك هنا",
            subtitle: "احصل على تقييم فوري لأهليتك للتأشيرة من خلال أداة التقييم المتقدمة لدينا. تعرف على فرصك قبل التقديم.",
            cta: "ابدأ",
            stat1: { value: "100%", label: "آمن وخاص" },
            stat2: { value: "94%", label: "معدل النجاح" },
            stat3: { value: "50K+", label: "التقييمات" },
            stat4: { value: "25+", label: "الدول" },
            form: { title: "ابدأ تقييمك", subtitle: "ملء التفاصيل الخاصة بك للحصول على تقييم أهلية التأشيرة الفوري" },
        },
        results: {
            title: "تقرير تقييم التأشيرة",
            downloadPdf: "تنزيل PDF",
            downloading: "جارٍ التنزيل...",
            copyIframe: "نسخ Iframe",
            copied: "تم النسخ!",
            apiKey: "مفتاح API",
            newEvaluation: "تقييم جديد",
            score: "درجة التقييم",
            summary: "ملخص",
            strengths: "نقاط القوة",
            improvements: "مجالات التحسين",
            recommendation: "توصية",
            nextSteps: "الخطوات التالية",
            timeline: "الجدول الزمني",
            additionalNotes: "ملاحظات إضافية",
            downloadFailed: "فشل تنزيل التقرير",
            another: "بدء تقييم آخر",
        },
        form: {
            name: "الاسم",
            email: "البريد الإلكتروني",
            country: "البلد",
            visaType: "نوع التأشيرة",
            selectCountry: "اختر البلد",
            selectVisaType: "اختر نوع التأشيرة",
            uploadDocuments: "تحميل المستندات",
            dragDrop: "اسحب وأفلت الملفات هنا أو انقر للتصفح",
            required: "مطلوب",
            optional: "اختياري",
            submitEvaluation: "إرسال للتقييم",
            submitting: "جارٍ الإرسال...",
            nameRequired: "الاسم مطلوب",
            emailRequired: "البريد الإلكتروني مطلوب",
            emailInvalid: "تنسيق البريد الإلكتروني غير صالح",
            countryRequired: "البلد مطلوب",
            visaTypeRequired: "نوع التأشيرة مطلوب",
            documentsRequired: "قم بتحميل مستند واحد مطلوب على الأقل",
            remove: "إزالة",
        },
        evaluation: {
            invalidLink: "رابط غير صالح",
            notFound: "لم نتمكن من العثور على تقييم للرابط المقدم.",
            ensureValid: "تأكد من أنك تستخدم عنوان URL صالح للتقرير.",
            loadingResults: "جارٍ تحميل نتائجك...",
            pleasewait: "يرجى الانتظار بينما نحصل على تقييمك.",
        },
    },
    zh: {
        home: {
            badge: "人工智能驱动的签证评估",
            title: "您的签证之旅从这里开始",
            subtitle: "使用我们先进的评估工具获得您的签证资格即时评估。在申请前了解您的机会。",
            cta: "开始",
            stat1: { value: "100%", label: "安全与隐私" },
            stat2: { value: "94%", label: "成功率" },
            stat3: { value: "50K+", label: "评估" },
            stat4: { value: "25+", label: "国家" },
            form: { title: "开始您的评估", subtitle: "填写您的详细信息以获得即时签证资格评估" },
        },
        results: {
            title: "签证评估报告",
            downloadPdf: "下载PDF",
            downloading: "下载中...",
            copyIframe: "复制Iframe",
            copied: "已复制！",
            apiKey: "API密钥",
            newEvaluation: "新评估",
            score: "评估分数",
            summary: "摘要",
            strengths: "优势",
            improvements: "改进领域",
            recommendation: "建议",
            nextSteps: "下一步",
            timeline: "时间表",
            additionalNotes: "附加说明",
            downloadFailed: "下载报告失败",
            another: "开始另一项评估",
        },
        form: {
            name: "姓名",
            email: "电子邮件",
            country: "国家",
            visaType: "签证类型",
            selectCountry: "选择国家",
            selectVisaType: "选择签证类型",
            uploadDocuments: "上传文档",
            dragDrop: "将文件拖放到此处或点击浏览",
            required: "必需",
            optional: "可选",
            submitEvaluation: "提交评估",
            submitting: "提交中...",
            nameRequired: "姓名为必填项",
            emailRequired: "电子邮件为必填项",
            emailInvalid: "电子邮件格式无效",
            countryRequired: "国家为必填项",
            visaTypeRequired: "签证类型为必填项",
            documentsRequired: "至少上传一个必需文档",
            remove: "删除",
        },
        evaluation: {
            invalidLink: "无效链接",
            notFound: "我们找不到提供链接的评估。",
            ensureValid: "确保您使用的是有效的报告URL。",
            loadingResults: "正在加载您的结果...",
            pleasewait: "请稍候，我们正在获取您的评估。",
        },
    },
    ja: {
        home: {
            badge: "AI駆動のビザ評価",
            title: "あなたのビザジャーニーはここから始まります",
            subtitle:
                "当社の高度な評価ツールを使用して、ビザの適格性の即座評価を取得してください。申請する前にあなたのチャンスを知ってください。",
            cta: "始める",
            stat1: { value: "100%", label: "安全とプライバシー" },
            stat2: { value: "94%", label: "成功率" },
            stat3: { value: "50K+", label: "評価" },
            stat4: { value: "25+", label: "国" },
            form: {
                title: "あなたの評価を開始してください",
                subtitle: "詳細を入力して、即座のビザ適格性評価を受け取ってください",
            },
        },
        results: {
            title: "ビザ評価レポート",
            downloadPdf: "PDFをダウンロード",
            downloading: "ダウンロード中...",
            copyIframe: "Iframeをコピー",
            copied: "コピーされました！",
            apiKey: "APIキー",
            newEvaluation: "新しい評価",
            score: "評価スコア",
            summary: "概要",
            strengths: "強み",
            improvements: "改善領域",
            recommendation: "推奨事項",
            nextSteps: "次のステップ",
            timeline: "タイムライン",
            additionalNotes: "追加のメモ",
            downloadFailed: "レポートのダウンロードに失敗しました",
            another: "別の評価を開始する",
        },
        form: {
            name: "名前",
            email: "メール",
            country: "国",
            visaType: "ビザの種類",
            selectCountry: "国を選択",
            selectVisaType: "ビザの種類を選択",
            uploadDocuments: "ドキュメントをアップロード",
            dragDrop: "ファイルをここにドラッグ＆ドロップするか、クリックして参照してください",
            required: "必須",
            optional: "オプション",
            submitEvaluation: "評価を送信",
            submitting: "送信中...",
            nameRequired: "名前は必須です",
            emailRequired: "メールは必須です",
            emailInvalid: "無効なメール形式",
            countryRequired: "国は必須です",
            visaTypeRequired: "ビザの種類は必須です",
            documentsRequired: "少なくとも1つの必須ドキュメントをアップロードしてください",
            remove: "削除",
        },
        evaluation: {
            invalidLink: "無効なリンク",
            notFound: "提供されたリンクの評価が見つかりませんでした。",
            ensureValid: "有効なレポートURLを使用していることを確認してください。",
            loadingResults: "結果を読み込んでいます...",
            pleasewait: "評価を取得していますので、お待ちください。",
        },
    },
}

type Language = keyof typeof translations
type LanguageContextType = {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
    // Initialize to 'en' by default. This is a client component so it's
    // safe to read localStorage on initial render. Using the lazy
    // initializer avoids calling setState inside an effect.
    const [language, setLanguageState] = useState<Language>(() => {
        try {
            const saved = localStorage.getItem("language") as Language | null
            if (saved && saved in translations) return saved
        } catch {
            /* ignore (e.g. private mode) */
        }
        return "en"
    })

    const setLanguage = (lang: Language) => {
        if (lang in translations) {
            setLanguageState(lang)
            localStorage.setItem("language", lang)
        }
    }

    const t = (key: string): string => {
        const keys = key.split(".")
        let value: unknown = translations[language]
        for (const k of keys) {
            // value may be nested objects, treat as a record for indexing
            value = (value as Record<string, unknown> | undefined)?.[k]
        }
        return typeof value === "string" ? value : key
    }

    // Always provide the context so client consumers can call `useLanguage`
    // during their initial render. The language value defaults to 'en'
    // until the effect above updates it from localStorage.
    return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error("useLanguage must be used within LanguageProvider")
    }
    return context
}
