"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

const translations = {
    en: {
        home: {
            badge: "AI-Powered Visa Assessment",
            title: "Your Visa Journey Starts Here",
            subtitle:
                "Get an instant evaluation of your visa eligibility with our advanced assessment tool. Know your chances before you apply.",
            cta: "Get Started",
            stat1: { value: "100%", label: "Secure & Private" },
            stat2: { value: "94%", label: "Success Rate" },
            stat3: { value: "50K+", label: "Evaluations" },
            stat4: { value: "25+", label: "Countries" },
            form: {
                title: "Start Your Evaluation",
                subtitle: "Fill in your details to receive an instant visa eligibility assessment",
            },
        },
        results: {
            title: "Visa Evaluation Report",
            downloadPdf: "Download PDF",
            downloading: "Downloading...",
            copyIframe: "Copy Iframe",
            copied: "Copied!",
            apiKey: "API Key",
            newEvaluation: "New Evaluation",
            score: "Evaluation Score",
            summary: "Summary",
            strengths: "Strengths",
            improvements: "Areas for Improvement",
            recommendation: "Recommendation",
            nextSteps: "Next Steps",
            timeline: "Timeline",
            additionalNotes: "Additional Notes",
            downloadFailed: "Failed to download report",
            another: "Start Another Evaluation",
            evaluationIdLabel: "Evaluation ID:",
            emailCopyNotice: "A copy of this report has been sent to your email",
            disclaimer1: "This is an automated evaluation for informational purposes only.",
            disclaimer2: "For official immigration advice, please consult with a licensed immigration professional.",
        },
        form: {
            name: "Name",
            email: "Email",
            country: "Country",
            visaType: "Visa Type",
            selectCountry: "Select country",
            selectVisaType: "Select visa type",
            uploadDocuments: "Upload Documents",
            dragDrop: "Drag and drop files here or click to browse",
            required: "Required",
            optional: "Optional",
            uploadedLabel: "Uploaded:",
            processingTime: "Processing Time",
            successRate: "Success Rate",
            requiredDocs: "Required Docs",
            optionalDocs: "Optional Docs",
            submitEvaluation: "Submit for Evaluation",
            submitting: "Submitting...",
            nameRequired: "Name is required",
            emailRequired: "Email is required",
            emailInvalid: "Invalid email format",
            countryRequired: "Country is required",
            visaTypeRequired: "Visa type is required",
            documentsRequired: "Upload at least one required document",
            remove: "Remove",
            uploadLimit: "You can upload up to {n} files.",
            unsupportedFormats: "One or more files have unsupported formats. Allowed: PDF, DOC, DOCX, JPG, PNG, WEBP.",
            fileTooLarge: "File too large. Max size is 10MB per file.",
        },
        evaluation: {
            invalidLink: "Invalid link",
            notFound: "We couldn't find an evaluation for the provided link.",
            ensureValid: "Ensure you are using a valid report URL.",
            loadingResults: "Loading your results...",
            pleasewait: "Please wait while we fetch your evaluation.",
            progressTitle: "Evaluation Progress",
            failedTitle: "Evaluation could not be completed",
            failedMsg: "One or more documents were found to be invalid or unreadable. Please re-upload the required documents.",
            backHome: "Back to Home",
            returnHome: "Return Home",
            invalidDocumentsAlert: "One or more documents appear to be faulty or unclear. Please re-upload the indicated documents and try again.",
            failedStart: "Failed to start evaluation job",
            timelineTitle: "AI Evaluation in Progress",
            timelineSubtitle: "Processing your visa application documents...",
            processing: "Processing",
            completed: "Completed",
            overallProgress: "Overall Progress",
            steps: {
                s1: { title: "Receiving documents", desc: "Uploading and processing your files..." },
                s2: { title: "Validating document format & clarity", desc: "Checking document quality and readability..." },
                s3: { title: "Running document verification with agent", desc: "AI agent analyzing document contents..." },
                s4: { title: "Computing visa eligibility score", desc: "Calculating your eligibility metrics..." },
                s5: { title: "Generating report & sending email", desc: "Finalizing your results..." },
            },
        },
        api: {
            title: "API Key for Evaluation",
            description: "Use this API key to access the evaluation data programmatically.",
            generating: "Generating API key...",
            failed: "Failed to generate API key. Please try again.",
            retry: "Retry",
            yourKey: "Your API Key",
            keepSecure: "Keep this key secure. It provides access to your evaluation data.",
            curlLabel: "Example cURL Command",
            curlHelp: "Use this command to fetch your evaluation data via the API.",
            endpoint: "API Endpoint",
            close: "Close",
        },
    },
    es: {
        home: {
            badge: "Evaluación de Visa Impulsada por IA",
            title: "Tu Viaje de Visa Comienza Aquí",
            subtitle:
                "Obtén una evaluación instantánea de tu elegibilidad de visa con nuestra herramienta de evaluación avanzada. Conoce tus posibilidades antes de solicitar.",
            cta: "Comenzar",
            stat1: { value: "100%", label: "Seguro y Privado" },
            stat2: { value: "94%", label: "Tasa de Éxito" },
            stat3: { value: "50K+", label: "Evaluaciones" },
            stat4: { value: "25+", label: "Países" },
            form: {
                title: "Comienza Tu Evaluación",
                subtitle: "Completa tus detalles para recibir una evaluación de elegibilidad de visa instantánea",
            },
        },
        results: {
            title: "Informe de Evaluación de Visa",
            downloadPdf: "Descargar PDF",
            downloading: "Descargando...",
            copyIframe: "Copiar Iframe",
            copied: "¡Copiado!",
            apiKey: "Clave API",
            newEvaluation: "Nueva Evaluación",
            score: "Puntuación de Evaluación",
            summary: "Resumen",
            strengths: "Fortalezas",
            improvements: "Áreas de Mejora",
            recommendation: "Recomendación",
            nextSteps: "Próximos Pasos",
            timeline: "Cronología",
            additionalNotes: "Notas Adicionales",
            downloadFailed: "Error al descargar el informe",
            another: "Comenzar Otra Evaluación",
        },
        form: {
            name: "Nombre",
            email: "Correo Electrónico",
            country: "País",
            visaType: "Tipo de Visa",
            selectCountry: "Seleccionar país",
            selectVisaType: "Seleccionar tipo de visa",
            uploadDocuments: "Subir Documentos",
            dragDrop: "Arrastra y suelta archivos aquí o haz clic para buscar",
            required: "Requerido",
            optional: "Opcional",
            submitEvaluation: "Enviar para Evaluación",
            submitting: "Enviando...",
            nameRequired: "El nombre es obligatorio",
            emailRequired: "El correo electrónico es obligatorio",
            emailInvalid: "Formato de correo electrónico no válido",
            countryRequired: "El país es obligatorio",
            visaTypeRequired: "El tipo de visa es obligatorio",
            documentsRequired: "Sube al menos un documento requerido",
            remove: "Eliminar",
            uploadedLabel: "Subido:",
            processingTime: "Tiempo de Procesamiento",
            successRate: "Tasa de Éxito",
            requiredDocs: "Documentos Requeridos",
            optionalDocs: "Documentos Opcionales",
            uploadLimit: "Puedes subir hasta {n} archivos.",
            unsupportedFormats: "Uno o más archivos tienen formatos no compatibles. Permitidos: PDF, DOC, DOCX, JPG, PNG, WEBP.",
            fileTooLarge: "Archivo demasiado grande. El tamaño máximo es 10MB por archivo.",
        },
        evaluation: {
            invalidLink: "Enlace no válido",
            notFound: "No pudimos encontrar una evaluación para el enlace proporcionado.",
            ensureValid: "Asegúrese de estar usando una URL de informe válida.",
            loadingResults: "Cargando tus resultados...",
            pleasewait: "Por favor espera mientras obtenemos tu evaluación.",
            progressTitle: "Progreso de Evaluación",
            failedTitle: "No se pudo completar la evaluación",
            failedMsg: "Uno o más documentos fueron encontrados como inválidos o ilegibles. Por favor vuelve a subir los documentos requeridos.",
            backHome: "Volver al Inicio",
            returnHome: "Volver al Inicio",
            invalidDocumentsAlert: "Uno o más documentos parecen ser defectuosos o poco claros. Por favor vuelve a subir los documentos indicados e intenta de nuevo.",
            failedStart: "Error al iniciar el trabajo de evaluación",
            timelineTitle: "Evaluación de IA en Progreso",
            timelineSubtitle: "Procesando tus documentos de solicitud de visa...",
            processing: "Procesando",
            completed: "Completado",
            overallProgress: "Progreso General",
            steps: {
                s1: { title: "Recibiendo documentos", desc: "Subiendo y procesando tus archivos..." },
                s2: { title: "Validando formato y claridad del documento", desc: "Verificando calidad y legibilidad del documento..." },
                s3: { title: "Ejecutando verificación de documentos con agente", desc: "Agente de IA analizando contenidos del documento..." },
                s4: { title: "Calculando puntuación de elegibilidad de visa", desc: "Calculando tus métricas de elegibilidad..." },
                s5: { title: "Generando informe y enviando correo electrónico", desc: "Finalizando tus resultados..." },
            },
        },
        results: {
            title: "Informe de Evaluación de Visa",
            downloadPdf: "Descargar PDF",
            downloading: "Descargando...",
            copyIframe: "Copiar Iframe",
            copied: "¡Copiado!",
            apiKey: "Clave API",
            newEvaluation: "Nueva Evaluación",
            score: "Puntuación de Evaluación",
            summary: "Resumen",
            strengths: "Fortalezas",
            improvements: "Áreas de Mejora",
            recommendation: "Recomendación",
            nextSteps: "Próximos Pasos",
            timeline: "Cronología",
            additionalNotes: "Notas Adicionales",
            downloadFailed: "Error al descargar el informe",
            another: "Comenzar Otra Evaluación",
            evaluationIdLabel: "ID de Evaluación:",
            emailCopyNotice: "Se ha enviado una copia de este informe a tu correo electrónico",
            disclaimer1: "Esta es una evaluación automatizada solo con fines informativos.",
            disclaimer2: "Para asesoramiento oficial de inmigración, consulta con un profesional de inmigración licenciado.",
        },
        api: {
            title: "Clave API para Evaluación",
            description: "Usa esta clave API para acceder a los datos de evaluación programáticamente.",
            generating: "Generando clave API...",
            failed: "Error al generar la clave API. Por favor intenta de nuevo.",
            retry: "Reintentar",
            yourKey: "Tu Clave API",
            keepSecure: "Mantén esta clave segura. Proporciona acceso a tus datos de evaluación.",
            curlLabel: "Comando cURL de Ejemplo",
            curlHelp: "Usa este comando para obtener tus datos de evaluación a través de la API.",
            endpoint: "Punto Final de API",
            close: "Cerrar",
        },
    },
    fr: {
        home: {
            badge: "Évaluation de Visa Alimentée par l'IA",
            title: "Votre Parcours Visa Commence Ici",
            subtitle:
                "Obtenez une évaluation instantanée de votre admissibilité aux visas avec notre outil d'évaluation avancé. Connaissez vos chances avant de postuler.",
            cta: "Commencer",
            stat1: { value: "100%", label: "Sécurisé et Privé" },
            stat2: { value: "94%", label: "Taux de Réussite" },
            stat3: { value: "50K+", label: "Évaluations" },
            stat4: { value: "25+", label: "Pays" },
            form: {
                title: "Commencez Votre Évaluation",
                subtitle: "Remplissez vos coordonnées pour recevoir une évaluation instantanée de l'admissibilité aux visas",
            },
        },
        results: {
            title: "Rapport d'Évaluation de Visa",
            downloadPdf: "Télécharger PDF",
            downloading: "Téléchargement...",
            copyIframe: "Copier Iframe",
            copied: "Copié!",
            apiKey: "Clé API",
            newEvaluation: "Nouvelle Évaluation",
            score: "Score d'Évaluation",
            summary: "Résumé",
            strengths: "Forces",
            improvements: "Axes d'Amélioration",
            recommendation: "Recommandation",
            nextSteps: "Prochaines Étapes",
            timeline: "Chronologie",
            additionalNotes: "Notes Supplémentaires",
            downloadFailed: "Échec du téléchargement du rapport",
            another: "Commencer une Autre Évaluation",
        },
        form: {
            name: "Nom",
            email: "Email",
            country: "Pays",
            visaType: "Type de Visa",
            selectCountry: "Sélectionner un pays",
            selectVisaType: "Sélectionner le type de visa",
            uploadDocuments: "Télécharger des Documents",
            dragDrop: "Glissez-déposez les fichiers ici ou cliquez pour parcourir",
            required: "Requis",
            optional: "Optionnel",
            submitEvaluation: "Soumettre pour Évaluation",
            submitting: "Envoi en cours...",
            nameRequired: "Le nom est requis",
            emailRequired: "L'email est requis",
            emailInvalid: "Format d'email invalide",
            countryRequired: "Le pays est requis",
            visaTypeRequired: "Le type de visa est requis",
            documentsRequired: "Téléchargez au moins un document requis",
            remove: "Supprimer",
            uploadedLabel: "Téléchargé:",
            processingTime: "Temps de Traitement",
            successRate: "Taux de Réussite",
            requiredDocs: "Documents Requis",
            optionalDocs: "Documents Optionnels",
            uploadLimit: "Vous pouvez télécharger jusqu'à {n} fichiers.",
            unsupportedFormats: "Un ou plusieurs fichiers ont des formats non pris en charge. Autorisés: PDF, DOC, DOCX, JPG, PNG, WEBP.",
            fileTooLarge: "Fichier trop volumineux. La taille maximale est de 10 Mo par fichier.",
        },
        evaluation: {
            invalidLink: "Lien invalide",
            notFound: "Nous n'avons pas pu trouver d'évaluation pour le lien fourni.",
            ensureValid: "Assurez-vous d'utiliser une URL de rapport valide.",
            loadingResults: "Chargement de vos résultats...",
            pleasewait: "Veuillez patienter pendant que nous récupérons votre évaluation.",
            progressTitle: "Progression de l'Évaluation",
            failedTitle: "L'évaluation n'a pas pu être achevée",
            failedMsg: "Un ou plusieurs documents ont été trouvés invalides ou illisibles. Veuillez retransmettre les documents requis.",
            backHome: "Retour à l'Accueil",
            returnHome: "Retour à l'Accueil",
            invalidDocumentsAlert: "Un ou plusieurs documents semblent défectueux ou peu clairs. Veuillez retransmettre les documents indiqués et réessayer.",
            failedStart: "Échec du démarrage de la tâche d'évaluation",
            timelineTitle: "Évaluation IA en Cours",
            timelineSubtitle: "Traitement de vos documents de demande de visa...",
            processing: "Traitement",
            completed: "Terminé",
            overallProgress: "Progression Globale",
            steps: {
                s1: { title: "Réception des documents", desc: "Téléchargement et traitement de vos fichiers..." },
                s2: { title: "Validation du format et de la clarté du document", desc: "Vérification de la qualité et de la lisibilité du document..." },
                s3: { title: "Exécution de la vérification des documents avec l'agent", desc: "Agent IA analysant le contenu du document..." },
                s4: { title: "Calcul du score d'admissibilité au visa", desc: "Calcul de vos métriques d'admissibilité..." },
                s5: { title: "Génération du rapport et envoi de l'email", desc: "Finalisation de vos résultats..." },
            },
        },
        results: {
            title: "Rapport d'Évaluation de Visa",
            downloadPdf: "Télécharger PDF",
            downloading: "Téléchargement...",
            copyIframe: "Copier Iframe",
            copied: "Copié!",
            apiKey: "Clé API",
            newEvaluation: "Nouvelle Évaluation",
            score: "Score d'Évaluation",
            summary: "Résumé",
            strengths: "Forces",
            improvements: "Axes d'Amélioration",
            recommendation: "Recommandation",
            nextSteps: "Prochaines Étapes",
            timeline: "Chronologie",
            additionalNotes: "Notes Supplémentaires",
            downloadFailed: "Échec du téléchargement du rapport",
            another: "Commencer une Autre Évaluation",
            evaluationIdLabel: "ID d'Évaluation:",
            emailCopyNotice: "Une copie de ce rapport a été envoyée à votre email",
            disclaimer1: "Il s'agit d'une évaluation automatisée à des fins informatives uniquement.",
            disclaimer2: "Pour des conseils officiels en matière d'immigration, veuillez consulter un professionnel de l'immigration agréé.",
        },
        api: {
            title: "Clé API pour l'Évaluation",
            description: "Utilisez cette clé API pour accéder aux données d'évaluation par programmation.",
            generating: "Génération de la clé API...",
            failed: "Échec de la génération de la clé API. Veuillez réessayer.",
            retry: "Réessayer",
            yourKey: "Votre Clé API",
            keepSecure: "Gardez cette clé en sécurité. Elle donne accès à vos données d'évaluation.",
            curlLabel: "Exemple de Commande cURL",
            curlHelp: "Utilisez cette commande pour récupérer vos données d'évaluation via l'API.",
            endpoint: "Point de Terminaison API",
            close: "Fermer",
        },
    },
    de: {
        home: {
            badge: "KI-gestützte Visabewertung",
            title: "Ihre Visareise Beginnt Hier",
            subtitle:
                "Erhalten Sie eine sofortige Bewertung Ihrer Visa-Berechtigung mit unserem fortschrittlichen Bewertungstool. Kennen Sie Ihre Chancen, bevor Sie sich bewerben.",
            cta: "Beginnen",
            stat1: { value: "100%", label: "Sicher & Privat" },
            stat2: { value: "94%", label: "Erfolgsrate" },
            stat3: { value: "50K+", label: "Bewertungen" },
            stat4: { value: "25+", label: "Länder" },
            form: {
                title: "Starten Sie Ihre Bewertung",
                subtitle: "Füllen Sie Ihre Daten aus, um eine sofortige Visaberechtigung-Bewertung zu erhalten",
            },
        },
        results: {
            title: "Visabewertungsbericht",
            downloadPdf: "PDF herunterladen",
            downloading: "Herunterladen...",
            copyIframe: "Iframe kopieren",
            copied: "Kopiert!",
            apiKey: "API-Schlüssel",
            newEvaluation: "Neue Bewertung",
            score: "Bewertungspunktzahl",
            summary: "Zusammenfassung",
            strengths: "Stärken",
            improvements: "Verbesserungsbereiche",
            recommendation: "Empfehlung",
            nextSteps: "Nächste Schritte",
            timeline: "Zeitplan",
            additionalNotes: "Zusätzliche Hinweise",
            downloadFailed: "Fehler beim Herunterladen des Berichts",
            another: "Eine Weitere Bewertung Starten",
            evaluationIdLabel: "Bewertungs-ID:",
            emailCopyNotice: "Eine Kopie dieses Berichts wurde an Ihre E-Mail gesendet",
            disclaimer1: "Dies ist eine automatisierte Bewertung nur zu Informationszwecken.",
            disclaimer2: "Für offizielle Einwanderungsberatung wenden Sie sich bitte an einen lizenzierten Einwanderungsexperten.",
        },
        form: {
            name: "Name",
            email: "E-Mail",
            country: "Land",
            visaType: "Visumart",
            selectCountry: "Land auswählen",
            selectVisaType: "Visumart auswählen",
            uploadDocuments: "Dokumente hochladen",
            dragDrop: "Dateien hier ablegen oder klicken zum Durchsuchen",
            required: "Erforderlich",
            optional: "Optional",
            submitEvaluation: "Zur Bewertung einreichen",
            submitting: "Wird eingereicht...",
            nameRequired: "Name ist erforderlich",
            emailRequired: "E-Mail ist erforderlich",
            emailInvalid: "Ungültiges E-Mail-Format",
            countryRequired: "Land ist erforderlich",
            visaTypeRequired: "Visumart ist erforderlich",
            documentsRequired: "Laden Sie mindestens ein erforderliches Dokument hoch",
            remove: "Entfernen",
            uploadedLabel: "Hochgeladen:",
            processingTime: "Bearbeitungszeit",
            successRate: "Erfolgsquote",
            requiredDocs: "Erforderliche Dokumente",
            optionalDocs: "Optionale Dokumente",
            uploadLimit: "Sie können bis zu {n} Dateien hochladen.",
            unsupportedFormats: "Eine oder mehrere Dateien haben nicht unterstützte Formate. Zulässig: PDF, DOC, DOCX, JPG, PNG, WEBP.",
            fileTooLarge: "Datei zu groß. Die maximale Größe beträgt 10 MB pro Datei.",
        },
        evaluation: {
            invalidLink: "Ungültiger Link",
            notFound: "Wir konnten keine Bewertung für den angegebenen Link finden.",
            ensureValid: "Stellen Sie sicher, dass Sie eine gültige Berichts-URL verwenden.",
            loadingResults: "Ihre Ergebnisse werden geladen...",
            pleasewait: "Bitte warten Sie, während wir Ihre Bewertung abrufen.",
            progressTitle: "Bewertungsfortschritt",
            failedTitle: "Bewertung konnte nicht abgeschlossen werden",
            failedMsg: "Ein oder mehrere Dokumente wurden als ungültig oder unleserlich befunden. Bitte laden Sie die erforderlichen Dokumente erneut hoch.",
            backHome: "Zurück zur Startseite",
            returnHome: "Zurück zur Startseite",
            invalidDocumentsAlert: "Ein oder mehrere Dokumente scheinen fehlerhaft oder unklar zu sein. Bitte laden Sie die angegebenen Dokumente erneut hoch und versuchen Sie es erneut.",
            failedStart: "Fehler beim Starten des Bewertungsvorgangs",
            timelineTitle: "KI-Bewertung läuft",
            timelineSubtitle: "Bearbeitung Ihrer Visumantragsdokumente...",
            processing: "Verarbeitung",
            completed: "Abgeschlossen",
            overallProgress: "Gesamtfortschritt",
            steps: {
                s1: { title: "Dokumente empfangen", desc: "Hochladen und Verarbeiten Ihrer Dateien..." },
                s2: { title: "Dokumentformat & Klarheit validieren", desc: "Überprüfung der Dokumentqualität und Lesbarkeit..." },
                s3: { title: "Dokumentenprüfung mit Agent durchführen", desc: "KI-Agent analysiert Dokumentinhalte..." },
                s4: { title: "Visumberechtigungspunktzahl berechnen", desc: "Berechnung Ihrer Berechtigungsmetriken..." },
                s5: { title: "Bericht erstellen & E-Mail senden", desc: "Finalisierung Ihrer Ergebnisse..." },
            },
        },
        api: {
            title: "API-Schlüssel für Bewertung",
            description: "Verwenden Sie diesen API-Schlüssel, um programmatisch auf die Bewertungsdaten zuzugreifen.",
            generating: "API-Schlüssel wird generiert...",
            failed: "Fehler beim Generieren des API-Schlüssels. Bitte versuchen Sie es erneut.",
            retry: "Erneut versuchen",
            yourKey: "Ihr API-Schlüssel",
            keepSecure: "Halten Sie diesen Schlüssel sicher. Er ermöglicht den Zugriff auf Ihre Bewertungsdaten.",
            curlLabel: "Beispiel cURL-Befehl",
            curlHelp: "Verwenden Sie diesen Befehl, um Ihre Bewertungsdaten über die API abzurufen.",
            endpoint: "API-Endpunkt",
            close: "Schließen",
        },
    },
    pt: {
        home: {
            badge: "Avaliação de Visto Alimentada por IA",
            title: "Sua Jornada de Visto Começa Aqui",
            subtitle:
                "Obtenha uma avaliação instantânea de sua elegibilidade de visto com nossa ferramenta de avaliação avançada. Conhece suas chances antes de se candidatar.",
            cta: "Começar",
            stat1: { value: "100%", label: "Seguro e Privado" },
            stat2: { value: "94%", label: "Taxa de Sucesso" },
            stat3: { value: "50K+", label: "Avaliações" },
            stat4: { value: "25+", label: "Países" },
            form: {
                title: "Comece Sua Avaliação",
                subtitle: "Preencha seus detalhes para receber uma avaliação instantânea de elegibilidade de visto",
            },
        },
        results: {
            title: "Relatório de Avaliação de Visto",
            downloadPdf: "Baixar PDF",
            downloading: "Baixando...",
            copyIframe: "Copiar Iframe",
            copied: "Copiado!",
            apiKey: "Chave API",
            newEvaluation: "Nova Avaliação",
            score: "Pontuação de Avaliação",
            summary: "Resumo",
            strengths: "Pontos Fortes",
            improvements: "Áreas de Melhoria",
            recommendation: "Recomendação",
            nextSteps: "Próximos Passos",
            timeline: "Cronograma",
            additionalNotes: "Notas Adicionais",
            downloadFailed: "Falha ao baixar o relatório",
            another: "Iniciar Outra Avaliação",
            evaluationIdLabel: "ID de Avaliação:",
            emailCopyNotice: "Uma cópia deste relatório foi enviada para seu email",
            disclaimer1: "Esta é uma avaliação automatizada apenas para fins informativos.",
            disclaimer2: "Para aconselhamento oficial de imigração, consulte um profissional de imigração licenciado.",
        },
        form: {
            name: "Nome",
            email: "Email",
            country: "País",
            visaType: "Tipo de Visto",
            selectCountry: "Selecionar país",
            selectVisaType: "Selecionar tipo de visto",
            uploadDocuments: "Enviar Documentos",
            dragDrop: "Arraste e solte arquivos aqui ou clique para navegar",
            required: "Obrigatório",
            optional: "Opcional",
            submitEvaluation: "Enviar para Avaliação",
            submitting: "Enviando...",
            nameRequired: "Nome é obrigatório",
            emailRequired: "Email é obrigatório",
            emailInvalid: "Formato de email inválido",
            countryRequired: "País é obrigatório",
            visaTypeRequired: "Tipo de visto é obrigatório",
            documentsRequired: "Envie pelo menos um documento obrigatório",
            remove: "Remover",
            uploadedLabel: "Enviado:",
            processingTime: "Tempo de Processamento",
            successRate: "Taxa de Sucesso",
            requiredDocs: "Documentos Obrigatórios",
            optionalDocs: "Documentos Opcionais",
            uploadLimit: "Você pode enviar até {n} arquivos.",
            unsupportedFormats: "Um ou mais arquivos têm formatos não suportados. Permitidos: PDF, DOC, DOCX, JPG, PNG, WEBP.",
            fileTooLarge: "Arquivo muito grande. O tamanho máximo é de 10MB por arquivo.",
        },
        evaluation: {
            invalidLink: "Link inválido",
            notFound: "Não conseguimos encontrar uma avaliação para o link fornecido.",
            ensureValid: "Certifique-se de estar usando uma URL de relatório válida.",
            loadingResults: "Carregando seus resultados...",
            pleasewait: "Aguarde enquanto buscamos sua avaliação.",
            progressTitle: "Progresso da Avaliação",
            failedTitle: "A avaliação não pôde ser concluída",
            failedMsg: "Um ou mais documentos foram encontrados como inválidos ou ilegíveis. Por favor, reenvie os documentos necessários.",
            backHome: "Voltar ao Início",
            returnHome: "Voltar ao Início",
            invalidDocumentsAlert: "Um ou mais documentos parecem estar com defeito ou pouco claros. Por favor, reenvie os documentos indicados e tente novamente.",
            failedStart: "Falha ao iniciar o trabalho de avaliação",
            timelineTitle: "Avaliação de IA em Progresso",
            timelineSubtitle: "Processando seus documentos de solicitação de visto...",
            processing: "Processando",
            completed: "Concluído",
            overallProgress: "Progresso Geral",
            steps: {
                s1: { title: "Recebendo documentos", desc: "Enviando e processando seus arquivos..." },
                s2: { title: "Validando formato e clareza do documento", desc: "Verificando qualidade e legibilidade do documento..." },
                s3: { title: "Executando verificação de documento com agente", desc: "Agente de IA analisando conteúdos do documento..." },
                s4: { title: "Calculando pontuação de elegibilidade de visto", desc: "Calculando suas métricas de elegibilidade..." },
                s5: { title: "Gerando relatório e enviando email", desc: "Finalizando seus resultados..." },
            },
        },
        api: {
            title: "Chave API para Avaliação",
            description: "Use esta chave API para acessar os dados de avaliação programaticamente.",
            generating: "Gerando chave API...",
            failed: "Falha ao gerar chave API. Por favor, tente novamente.",
            retry: "Tentar Novamente",
            yourKey: "Sua Chave API",
            keepSecure: "Mantenha esta chave segura. Ela fornece acesso aos seus dados de avaliação.",
            curlLabel: "Comando cURL de Exemplo",
            curlHelp: "Use este comando para buscar seus dados de avaliação através da API.",
            endpoint: "Ponto Final da API",
            close: "Fechar",
        },
    },
    ar: {
        home: {
            badge: "تقييم التأشيرة بقوة الذكاء الاصطناعي",
            title: "تبدأ رحلة التأشيرة الخاصة بك هنا",
            subtitle: "احصل على تقييم فوري لأهليتك للتأشيرة من خلال أداة التقييم المتقدمة لدينا. تعرف على فرصك قبل التقديم.",
            cta: "ابدأ",
            stat1: { value: "100%", label: "آمن وخاص" },
            stat2: { value: "94%", label: "معدل النجاح" },
            stat3: { value: "50K+", label: "التقييمات" },
            stat4: { value: "25+", label: "الدول" },
            form: { title: "ابدأ تقييمك", subtitle: "ملء التفاصيل الخاصة بك للحصول على تقييم أهلية التأشيرة الفوري" },
        },
        results: {
            title: "تقرير تقييم التأشيرة",
            downloadPdf: "تنزيل PDF",
            downloading: "جارٍ التنزيل...",
            copyIframe: "نسخ Iframe",
            copied: "تم النسخ!",
            apiKey: "مفتاح API",
            newEvaluation: "تقييم جديد",
            score: "درجة التقييم",
            summary: "ملخص",
            strengths: "نقاط القوة",
            improvements: "مجالات التحسين",
            recommendation: "توصية",
            nextSteps: "الخطوات التالية",
            timeline: "الجدول الزمني",
            additionalNotes: "ملاحظات إضافية",
            downloadFailed: "فشل تنزيل التقرير",
            another: "بدء تقييم آخر",
            evaluationIdLabel: "معرف التقييم:",
            emailCopyNotice: "تم إرسال نسخة من هذا التقرير إلى بريدك الإلكتروني",
            disclaimer1: "هذا تقييم آلي لأغراض إعلامية فقط.",
            disclaimer2: "للحصول على مشورة هجرة رسمية، يرجى التشاور مع محترف هجرة مرخص.",
        },
        form: {
            name: "الاسم",
            email: "البريد الإلكتروني",
            country: "البلد",
            visaType: "نوع التأشيرة",
            selectCountry: "اختر البلد",
            selectVisaType: "اختر نوع التأشيرة",
            uploadDocuments: "تحميل المستندات",
            dragDrop: "اسحب وأفلت الملفات هنا أو انقر للتصفح",
            required: "مطلوب",
            optional: "اختياري",
            submitEvaluation: "إرسال للتقييم",
            submitting: "جارٍ الإرسال...",
            nameRequired: "الاسم مطلوب",
            emailRequired: "البريد الإلكتروني مطلوب",
            emailInvalid: "تنسيق البريد الإلكتروني غير صالح",
            countryRequired: "البلد مطلوب",
            visaTypeRequired: "نوع التأشيرة مطلوب",
            documentsRequired: "قم بتحميل مستند واحد مطلوب على الأقل",
            remove: "إزالة",
            uploadedLabel: "تم التحميل:",
            processingTime: "وقت المعالجة",
            successRate: "معدل النجاح",
            requiredDocs: "المستندات المطلوبة",
            optionalDocs: "المستندات الاختيارية",
            uploadLimit: "يمكنك تحميل ما يصل إلى {n} ملفات.",
            unsupportedFormats: "واحد أو أكثر من الملفات لها تنسيقات غير مدعومة. المسموح به: PDF, DOC, DOCX, JPG, PNG, WEBP.",
            fileTooLarge: "الملف كبير جداً. الحد الأقصى للحجم هو 10 ميجابايت لكل ملف.",
        },
        evaluation: {
            invalidLink: "رابط غير صالح",
            notFound: "لم نتمكن من العثور على تقييم للرابط المقدم.",
            ensureValid: "تأكد من أنك تستخدم عنوان URL صالح للتقرير.",
            loadingResults: "جارٍ تحميل نتائجك...",
            pleasewait: "يرجى الانتظار بينما نحصل على تقييمك.",
            progressTitle: "تقدم التقييم",
            failedTitle: "لم يتمكن من إكمال التقييم",
            failedMsg: "تم العثور على واحد أو أكثر من المستندات غير صالحة أو غير قابلة للقراءة. يرجى إعادة تحميل المستندات المطلوبة.",
            backHome: "العودة إلى الصفحة الرئيسية",
            returnHome: "العودة إلى الصفحة الرئيسية",
            invalidDocumentsAlert: "يبدو أن مستنداً واحداً أو أكثر معيبة أو غير واضحة. يرجى إعادة تحميل المستندات المشار إليها والمحاولة مرة أخرى.",
            failedStart: "فشل بدء عملية التقييم",
            timelineTitle: "تقييم الذكاء الاصطناعي قيد التنفيذ",
            timelineSubtitle: "معالجة مستندات طلب التأشيرة الخاصة بك...",
            processing: "جارٍ المعالجة",
            completed: "مكتمل",
            overallProgress: "التقدم الإجمالي",
            steps: {
                s1: { title: "استلام المستندات", desc: "تحميل ومعالجة ملفاتك..." },
                s2: { title: "التحقق من تنسيق ووضوح المستند", desc: "فحص جودة وقراءة المستند..." },
                s3: { title: "تشغيل التحقق من المستند بواسطة الوكيل", desc: "وكيل الذكاء الاصطناعي يحلل محتويات المستند..." },
                s4: { title: "حساب درجة أهلية التأشيرة", desc: "حساب مقاييس أهليتك..." },
                s5: { title: "إنشاء التقرير وإرسال البريد الإلكتروني", desc: "إنهاء نتائجك..." },
            },
        },
        api: {
            title: "مفتاح API للتقييم",
            description: "استخدم مفتاح API هذا للوصول إلى بيانات التقييم برمجياً.",
            generating: "جارٍ إنشاء مفتاح API...",
            failed: "فشل إنشاء مفتاح API. يرجى المحاولة مرة أخرى.",
            retry: "إعادة المحاولة",
            yourKey: "مفتاح API الخاص بك",
            keepSecure: "احتفظ بهذا المفتاح بشكل آمن. إنه يوفر الوصول إلى بيانات التقييم الخاصة بك.",
            curlLabel: "مثال أمر cURL",
            curlHelp: "استخدم هذا الأمر لجلب بيانات التقييم الخاصة بك عبر API.",
            endpoint: "نقطة نهاية API",
            close: "إغلاق",
        },
    },
    zh: {
        home: {
            badge: "人工智能驱动的签证评估",
            title: "您的签证之旅从这里开始",
            subtitle: "使用我们先进的评估工具获得您的签证资格即时评估。在申请前了解您的机会。",
            cta: "开始",
            stat1: { value: "100%", label: "安全与隐私" },
            stat2: { value: "94%", label: "成功率" },
            stat3: { value: "50K+", label: "评估" },
            stat4: { value: "25+", label: "国家" },
            form: { title: "开始您的评估", subtitle: "填写您的详细信息以获得即时签证资格评估" },
        },
        results: {
            title: "签证评估报告",
            downloadPdf: "下载PDF",
            downloading: "下载中...",
            copyIframe: "复制Iframe",
            copied: "已复制！",
            apiKey: "API密钥",
            newEvaluation: "新评估",
            score: "评估分数",
            summary: "摘要",
            strengths: "优势",
            improvements: "改进领域",
            recommendation: "建议",
            nextSteps: "下一步",
            timeline: "时间表",
            additionalNotes: "附加说明",
            downloadFailed: "下载报告失败",
            another: "开始另一项评估",
            evaluationIdLabel: "评估ID：",
            emailCopyNotice: "此报告的副本已发送至您的电子邮件",
            disclaimer1: "这是一个自动评估，仅供参考。",
            disclaimer2: "对于官方移民建议，请咨询持有许可证的移民专业人士。",
        },
        form: {
            name: "姓名",
            email: "电子邮件",
            country: "国家",
            visaType: "签证类型",
            selectCountry: "选择国家",
            selectVisaType: "选择签证类型",
            uploadDocuments: "上传文档",
            dragDrop: "将文件拖放到此处或点击浏览",
            required: "必需",
            optional: "可选",
            submitEvaluation: "提交评估",
            submitting: "提交中...",
            nameRequired: "姓名为必填项",
            emailRequired: "电子邮件为必填项",
            emailInvalid: "电子邮件格式无效",
            countryRequired: "国家为必填项",
            visaTypeRequired: "签证类型为必填项",
            documentsRequired: "至少上传一个必需文档",
            remove: "删除",
            uploadedLabel: "已上传：",
            processingTime: "处理时间",
            successRate: "成功率",
            requiredDocs: "必需文档",
            optionalDocs: "可选文档",
            uploadLimit: "您最多可上传{n}个文件。",
            unsupportedFormats: "一个或多个文件格式不支持。允许的格式：PDF, DOC, DOCX, JPG, PNG, WEBP。",
            fileTooLarge: "文件过大。每个文件的最大大小为10MB。",
        },
        evaluation: {
            invalidLink: "无效链接",
            notFound: "我们找不到提供链接的评估。",
            ensureValid: "确保您使用的是有效的报告URL。",
            loadingResults: "正在加载您的结果...",
            pleasewait: "请稍候，我们正在获取您的评估。",
            progressTitle: "评估进度",
            failedTitle: "评估无法完成",
            failedMsg: "发现一个或多个文档无效或不可读。请重新上传所需文档。",
            backHome: "返回首页",
            returnHome: "返回首页",
            invalidDocumentsAlert: "一个或多个文档似乎有问题或不清楚。请重新上传指定的文档并重试。",
            failedStart: "启动评估作业失败",
            timelineTitle: "AI评估进行中",
            timelineSubtitle: "正在处理您的签证申请文件...",
            processing: "处理中",
            completed: "已完成",
            overallProgress: "总体进度",
            steps: {
                s1: { title: "接收文档", desc: "上传和处理您的文件..." },
                s2: { title: "验证文档格式和清晰度", desc: "检查文档质量和可读性..." },
                s3: { title: "运行代理文档验证", desc: "AI代理分析文档内容..." },
                s4: { title: "计算签证资格分数", desc: "计算您的资格指标..." },
                s5: { title: "生成报告并发送电子邮件", desc: "完成您的结果..." },
            },
        },
        api: {
            title: "评估API密钥",
            description: "使用此API密钥以编程方式访问评估数据。",
            generating: "正在生成API密钥...",
            failed: "生成API密钥失败。请重试。",
            retry: "重试",
            yourKey: "您的API密钥",
            keepSecure: "请安全保管此密钥。它提供对您评估数据的访问权限。",
            curlLabel: "cURL命令示例",
            curlHelp: "使用此命令通过API获取您的评估数据。",
            endpoint: "API端点",
            close: "关闭",
        },
    },
    ja: {
        home: {
            badge: "AI駆動のビザ評価",
            title: "あなたのビザジャーニーはここから始まります",
            subtitle:
                "当社の高度な評価ツールを使用して、ビザの適格性の即座評価を取得してください。申請する前にあなたのチャンスを知ってください。",
            cta: "始める",
            stat1: { value: "100%", label: "安全とプライバシー" },
            stat2: { value: "94%", label: "成功率" },
            stat3: { value: "50K+", label: "評価" },
            stat4: { value: "25+", label: "国" },
            form: {
                title: "あなたの評価を開始してください",
                subtitle: "詳細を入力して、即座のビザ適格性評価を受け取ってください",
            },
        },
        results: {
            title: "ビザ評価レポート",
            downloadPdf: "PDFをダウンロード",
            downloading: "ダウンロード中...",
            copyIframe: "Iframeをコピー",
            copied: "コピーされました！",
            apiKey: "APIキー",
            newEvaluation: "新しい評価",
            score: "評価スコア",
            summary: "概要",
            strengths: "強み",
            improvements: "改善領域",
            recommendation: "推奨事項",
            nextSteps: "次のステップ",
            timeline: "タイムライン",
            additionalNotes: "追加のメモ",
            downloadFailed: "レポートのダウンロードに失敗しました",
            another: "別の評価を開始する",
            evaluationIdLabel: "評価ID：",
            emailCopyNotice: "このレポートのコピーがあなたのメールに送信されました",
            disclaimer1: "これは情報提供のみを目的とした自動評価です。",
            disclaimer2: "公式な移民アドバイスについては、免許を持つ移民専門家にご相談ください。",
        },
        form: {
            name: "名前",
            email: "メール",
            country: "国",
            visaType: "ビザの種類",
            selectCountry: "国を選択",
            selectVisaType: "ビザの種類を選択",
            uploadDocuments: "ドキュメントをアップロード",
            dragDrop: "ファイルをここにドラッグ＆ドロップするか、クリックして参照してください",
            required: "必須",
            optional: "オプション",
            submitEvaluation: "評価を送信",
            submitting: "送信中...",
            nameRequired: "名前は必須です",
            emailRequired: "メールは必須です",
            emailInvalid: "無効なメール形式",
            countryRequired: "国は必須です",
            visaTypeRequired: "ビザの種類は必須です",
            documentsRequired: "少なくとも1つの必須ドキュメントをアップロードしてください",
            remove: "削除",
            uploadedLabel: "アップロード済み：",
            processingTime: "処理時間",
            successRate: "成功率",
            requiredDocs: "必須ドキュメント",
            optionalDocs: "オプションドキュメント",
            uploadLimit: "最大{n}個のファイルをアップロードできます。",
            unsupportedFormats: "、1つ以上のファイルがサポートされていない形式です。許可されている形式：PDF, DOC, DOCX, JPG, PNG, WEBP。",
            fileTooLarge: "ファイルが大きすぎます。ファイルあたりの最大サイズは10MBです。",
        },
        evaluation: {
            invalidLink: "無効なリンク",
            notFound: "提供されたリンクの評価が見つかりませんでした。",
            ensureValid: "有効なレポートURLを使用していることを確認してください。",
            loadingResults: "結果を読み込んでいます...",
            pleasewait: "評価を取得していますので、お待ちください。",
            progressTitle: "評価の進行状況",
            failedTitle: "評価を完了できませんでした",
            failedMsg: "、1つ以上のドキュメントが無効または読み取り不能と判明しました。必要なドキュメントを再アップロードしてください。",
            backHome: "ホームに戻る",
            returnHome: "ホームに戻る",
            invalidDocumentsAlert: "、1つ以上のドキュメントに不備または不明瞭な点があるようです。指定されたドキュメントを再アップロードして再試行してください。",
            failedStart: "評価ジョブの開始に失敗しました",
            timelineTitle: "AI評価実行中",
            timelineSubtitle: "ビザ申請書類を処理中...",
            processing: "処理中",
            completed: "完了",
            overallProgress: "全体の進行状況",
            steps: {
                s1: { title: "ドキュメントを受信中", desc: "ファイルをアップロードおよび処理中..." },
                s2: { title: "ドキュメントの形式と明瞭さを検証中", desc: "ドキュメントの品質と可読性を確認中..." },
                s3: { title: "エージェントでドキュメント検証を実行中", desc: "AIエージェントがドキュメント内容を分析中..." },
                s4: { title: "ビザ適格性スコアを計算中", desc: "適格性指標を計算中..." },
                s5: { title: "レポートを生成しメールを送信中", desc: "結果を仕上げ中..." },
            },
        },
        api: {
            title: "評価用APIキー",
            description: "このAPIキーを使用して、プログラムで評価データにアクセスします。",
            generating: "APIキーを生成中...",
            failed: "APIキーの生成に失敗しました。もう一度お試しください。",
            retry: "再試行",
            yourKey: "あなたのAPIキー",
            keepSecure: "このキーを安全に保管してください。評価データへのアクセスを提供します。",
            curlLabel: "cURLコマンドの例",
            curlHelp: "このコマンドを使用してAPI経由で評価データを取得します。",
            endpoint: "APIエンドポイント",
            close: "閉じる",
        },
    },
}

type Language = keyof typeof translations
type LanguageContextType = {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
    // Initialize to 'en' by default. This is a client component so it's
    // safe to read localStorage on initial render. Using the lazy
    // initializer avoids calling setState inside an effect.
    const [language, setLanguageState] = useState<Language>(() => {
        try {
            const saved = localStorage.getItem("language") as Language | null
            if (saved && saved in translations) return saved
        } catch {
            /* ignore (e.g. private mode) */
        }
        return "en"
    })

    const setLanguage = (lang: Language) => {
        if (lang in translations) {
            setLanguageState(lang)
            localStorage.setItem("language", lang)
        }
    }

    const t = (key: string): string => {
        const keys = key.split(".")
        // Try current language first
        let value: unknown = translations[language]
        for (const k of keys) {
            value = (value as Record<string, unknown> | undefined)?.[k]
        }
        if (typeof value === "string") return value

        // Fallback to English
        let fallback: unknown = translations.en
        for (const k of keys) {
            fallback = (fallback as Record<string, unknown> | undefined)?.[k]
        }
        return typeof fallback === "string" ? fallback : key
    }

    // Always provide the context so client consumers can call `useLanguage`
    // during their initial render. The language value defaults to 'en'
    // until the effect above updates it from localStorage.
    return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error("useLanguage must be used within LanguageProvider")
    }
    return context
}
